name: Add Issue to Jira Board

on:
  issues:
    types:
      - opened

jobs:
  call-workflow-jira-ccreate:
    uses: ministryofjustice/cloud-operations-github-actions/.github/workflows/jira-create-workflow-call.yml@main
    secrets:
      JIRA_SECRET: ${{ secrets.JIRA_SECRET }}
