name: Add Issue to Jira Board

on:
  issues:
    types:
      - opened

jobs:
  call-workflow-jira-create:
    uses: ministryofjustice/cloud-operations-github-actions/.github/workflows/issue-to-jira.yml@main
    secrets:
      JIRA_SECRET: ${{ secrets.JIRA_SECRET }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_URL: ${{ secrets.JIRA_URL }}
