name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  issues-to-project:
    steps:
      - uses: ministryofjustice/cloud-operations/.github/workflows/issue-to-project.yml@main
