name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  call-workflow:
    uses: ministryofjustice/cloud-operations-github-actions/.github/workflows/issue-to-project.yml@main
    secrets:
      TECH_SERVICES_GITHUB_TOKEN: ${{ secrets.TECH_SERVICES_GITHUB_TOKEN }}
